name: PasswordProtect
main: de.dustplanet.passwordprotect.PasswordProtect
description: Force a password to play on the server
version: ${project.version}${build.number}
author: xGhOsTkiLLeRx
authors: [DisabledHamster]
website: https://dev.bukkit.org/projects/passwordprotect
commands:
  login:
    description: Login using this server's password
    usage: /<command> password
  setjaillocation:
    description: Set the password jail to your current location
    aliases: [setjail, setjailarea, setpasswordjail]
    usage: /<command>
  setpassword:
    description: Set the password required for non-ops to play on this server
    usage: /<command> password
  password:
    description: Get the password
    usage: /<command>
permissions:
  passwordprotect.*:
    description: Gives access to all PasswordProtect permissions
    children:
      passwordprotect.getpassword: true
      passwordprotect.setpassword: true
      passwordprotect.setjailarea: true
  passwordprotect.nopassword:
    description: Allows you to bypass login
    default: false
  passwordprotect.getpassword:
    description: Allows you to get the password
    default: op
  passwordprotect.setpassword:
    description: Allows you to set the password
    default: op
  passwordprotect.setjailarea:
    description: Allows you to set the jail area
    default: op
