name: Build the plugin

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [11, 17]

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Version information
      run: |
        java -version
        mvn --version

    - name: Build with Maven
      run: mvn -D"http.keepAlive=false" -D"maven.wagon.http.pool=false" -D"maven.wagon.httpconnectionManager.ttlSeconds=120" -DskipTests=true -B -V clean package
      uses: actions/upload-artifact@v4
      with:
        name: PasswordProtect.jar
        path: PasswordProtect.jar

  auto-merge:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Automatically merge dependabot upgrades
        uses: fastify/github-action-merge-dependabot@v3.9.1
        with:
          target: minor
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: PasswordProtect

      - name: Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.run_number }}
          release_name: PasswordProtect ${{ github.run_number }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./PasswordProtect.jar
          asset-name: PasswordProtect-v${{ github.run_number }}.jar
          asset-content-type: application/jar
