name: Build and Release Plugin

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Version information
      run: |
        java -version
        mvn --version

    - name: Build with Maven
      run: mvn -D"http.keepAlive=false" -D"maven.wagon.http.pool=false" -D"maven.wagon.httpconnectionManager.ttlSeconds=120" -DskipTests=true -B -V clean package
    - run: mkdir staging && cp target/*.jar staging
    - run: ls

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: PasswordProtect-${{ matrix.os }}-${{ matrix.java }}.jar
        path: staging
    - run: ls
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        path: ./

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: PasswordProtect ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: PasswordProtect-${{ matrix.os }}-${{ matrix.java }}.jar
        asset_name: PasswordProtect-${{ matrix.os }}-${{ matrix.java }}.jar
        asset_content_type: application/java-archive
